torrent0:
   torrent-file: samplepictures.torrent
   file-dir: torrents
   download-dir: downloads

torrent1:
   torrent-file: samplepictures.torrent
   file-dir: torrents
   download-dir: downloads