torrent0:
   torrent-file: samplepictures.torrent
   file-dir: torrents
   download-dir: downloads/0

torrent1:
   torrent-file: samplepictures-2.torrent
   file-dir: torrents
   download-dir: downloads/1
